// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okmttxaegfbpxtuilzuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbXR0eGFlZ2ZicHh0dWlsenVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTcyMjAsImV4cCI6MjA3NDEzMzIyMH0.N9WGkEzjEjv_z1q5yaL04iJZH7IAz_Y8t0y4XzWKu_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});